// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AddJson.Models
{
    public partial class l
    {
        public string CondicaoNome{get;set;}
        public List<Capitulo> Capitulo{get;set;}
    }
}
